DROP TABLE IF EXISTS COIN; 

CREATE TABLE COIN (  
	ID INT AUTO_INCREMENT  PRIMARY KEY,  
	VALUE DECIMAL(10, 2) NOT NULL,  
	COUNT INT NOT NULL  
); 

INSERT INTO COIN(ID, VALUE, COUNT) VALUES (1, '0.01', 100);    
INSERT INTO COIN(ID, VALUE, COUNT) VALUES (2, '0.05', 100);    
INSERT INTO COIN(ID, VALUE, COUNT) VALUES (3, '0.10', 100);  
INSERT INTO COIN(ID, VALUE, COUNT) VALUES (4, '0.25', 100);  